### ISSUE TITLE
America/Godthab results in :time_zone_not_found

### ISSUE THREAD

**Issue by mathieuprog** [hrzndhrn/time_zone_info#28]
Looking for a period on time zone America/Godthab results in an error `:time_zone_not_found`.
It was renamed to America/Nuuk, but Godthab should be still supported?

>    To reflect current usage in English better, America/Godthab has
>    been renamed to America/Nuuk.  A backwards-compatibility link
>    remains for the old name.

**Comment by NickNeck** [comment]
Thank you for your contribution. For now, the IANA file `backward` is not included to the default `files`. I will add `backward` to the next version.
