### ISSUE TITLE
(CondClauseError) no cond clause evaluated to a truthy value

### ISSUE THREAD

**Issue by mathieuprog** [hrzndhrn/time_zone_info#4]
`iex> DateTime.from_naive(~N[1994-09-24 22:00:00], "Asia/Aqtau", TimeZoneInfo.TimeZoneDatabase)`

> ** (CondClauseError) no cond clause evaluated to a truthy value
>      code: |> Enum.each(fn filename ->
>      stacktrace:
>        (time_zone_info 0.1.1) lib/time_zone_info/time_zone_database.ex:180: TimeZoneInfo.TimeZoneDatabase.to_periods/3
>        (elixir 1.10.2) lib/calendar/datetime.ex:267: DateTime.from_naive/3

**Comment by NickNeck** [comment]
Hello, thanks for reporting this. I will have a look.

**Comment by NickNeck** [comment]
Fixed.

**Comment by mathieuprog** [comment]
Hello, are you sure this is fixed?

```
$ iex -S mix
iex> DateTime.from_naive(~N[1994-09-24 22:00:00], "Asia/Aqtau", TimeZoneInfo.TimeZoneDatabase)
```

> ** (CondClauseError) no cond clause evaluated to a truthy value

**Comment by NickNeck** [comment]
Yes, this is fixed
```
$> mix hex.outdated                      
Dependency      Current  Latest  Update possible
time_zone_info  0.2.0    0.2.0
$> iex -S mix                           
iex(1)> DateTime.from_naive(~N[1994-09-24 22:00:00], "Asia/Aqtau", TimeZoneInfo.TimeZoneDatabase)
{:ok, #DateTime<1994-09-24 22:00:00+06:00 +06 Asia/Aqtau>}
```
But I have closed this issue to early. The real fixe was merged to the `master` 10 hours ago, because I have found a bunch of bugs. Sorry for that.
