### ISSUE TITLE
FunctionClauseError calling time_zone_period_from_utc_iso_days with negative year and another time zone than utc

### ISSUE THREAD

**Issue by mathieuprog** [hrzndhrn/time_zone_info#41]
```elixir
iso_days = Calendar.ISO.naive_datetime_to_iso_days(-1, 1, 1, 0, 0, 0, {0, 6})

TimeZoneInfo.TimeZoneDatabase.time_zone_period_from_utc_iso_days(iso_days, "Europe/Brussels")
```

> ** (FunctionClauseError) no function clause matching in TimeZoneInfo.TimeZoneDatabase.to_period/2

    The following arguments were given to TimeZoneInfo.TimeZoneDatabase.to_period/2:

        # 1
        nil

        # 2
        {-365, {0, 86400000000}}

    Attempted function clauses (showing 2 out of 2):

        defp to_period({utc_offset, rule_name, {_, _} = format}, {_, {_, _}} = iso_days)
        defp to_period({utc_offset, std_offset, zone_abbr, wall_period}, _iso_days)

    (time_zone_info 0.6.3) lib/time_zone_info/time_zone_database.ex:90: TimeZoneInfo.TimeZoneDatabase.to_period/2
    iex:31: (file)

**Comment by NickNeck** [comment]
Thanks for reporting. I will take a look.
