### ISSUE TITLE
Documentation typo for turning off updater

### ISSUE THREAD

**Issue by GregorGrasselli** [hrzndhrn/time_zone_info#46]
The line
https://github.com/hrzndhrn/time_zone_info/blob/ab7655984fe3bc95466d080c02de5b5ad9e02275/README.md?plain=1#L73
states that by default the updater is turned off using `updater: :disabled`. Doing that does not work. Doing `update: :disabled` seems to do the job (the diff is deleting the `r` :smile: ).

**Comment by NickNeck** [comment]
Thanks a lot.
